gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh
gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh
gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh
gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh
gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh
gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh
gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh
gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh
gnome-terminal -- docker run --gpus all -it --rm -e DISPLAY=$DISPLAY --net=host -v $(pwd):/workspace -w /workspace/FastMOT umair:latest ./run_example.sh